import csv
import os


IMAGES_FOLDER_FP = "data/UrbanWaste-images-10k-right"

# add a typing alias
ImageMetadata = tuple[str, int, float, float]

def get_image_fps() -> list[ImageMetadata]:
    """
    Get a list of all image file paths with their associated metadata.
    Each image file path is coupled with the heading and pitch angles extracted from the file name. The file name format is expected to be:
    "pano_{4-digit_id}_{6-digit-id}_heading{heading-with-two-decimal-places}_pitch{pitch-with-two-decimal-places}_right90_square_fov90.0_640x640.jpg"
    """
    res = []
    for folder in os.listdir(IMAGES_FOLDER_FP):
        if folder.startswith("year_"):
            year = folder.split("_")[1]
            subfolder_fps = [os.path.join(IMAGES_FOLDER_FP, folder, img) for img in os.listdir(os.path.join(IMAGES_FOLDER_FP, folder))]
            subfolder_fps = [fp for fp in subfolder_fps if not '.' in fp]
            image_fps = [os.path.join(subfolder_fp, fp) for subfolder_fp in subfolder_fps for fp in os.listdir(subfolder_fp) if fp.endswith(".jpg")]
            # Extract heading and pitch from each image file path
            image_fps = [
                (
                    fp,
                    int(year),
                    float(os.path.basename(fp).split('_')[3].lstrip('heading')),
                    float(os.path.basename(fp).split('_')[4].lstrip('pitch'))
                )
                for fp in image_fps
            ]
            res.extend(image_fps)
    print(f"Total images loaded: {len(res)}")
    return res

DinoData = tuple[str, float, int] # (file path, max confidence, number of objects detected)

def get_dino_labelling_data() -> list[DinoData]:
    """
    Reads the CSV file generated by dino_labelling.py and returns a list of tuples containing the file path, max confidence, and number of objects detected for each image.
    """
    data = []
    with open("data/grounding_dino_scores.csv", mode='r', newline='', encoding='utf-8') as f:
        reader = csv.DictReader(f)
        for row in reader:
            data.append((row["filename"], float(row["max_confidence"]), int(row["waste_objects_detected"])))
    return data